### ISSUE TITLE
TypeError: Cannot read property 'tap' of undefined. (Version 2.0.0. doesn't work for Webpack 4.x.x)

### ISSUE THREAD

**Issue by aclever** [elliottsj/generate-json-webpack-plugin#106]
Hi everyone,

Today, I updated packages to latest versions and this package stop working with error:

```
TypeError: Cannot read property 'tap' of undefined...

```

I've installed version 1.0.0 and it fixed. Just want to note this problem.

**Comment by elliottsj** [comment]
Thanks for the issue.

Version 2.0.0 supports webpack 5 only: https://github.com/elliottsj/generate-json-webpack-plugin/releases/tag/v2.0.0
