### ISSUE TITLE
Generate .json file from source-module by path to it

### ISSUE THREAD

**Issue by bipycxp** [elliottsj/generate-json-webpack-plugin#38]
Something like:
```javascript
// source.js
module.exports = {
  foo: 'bar'
}

// webpack.config.js
const GenerateJsonPlugin = require('generate-json-webpack-plugin');

module.exports = {
  // ...
  plugins: [
    // ...
    new GenerateJsonPlugin('my-file.json', __dirname + '/source.js')
  ]
  // ...
};
```

**Comment by bipycxp** [comment]
#39

**Comment by elliottsj** [comment]
Hey, thanks for the issue + PR. Does your use case require that you pass an absolute path to the plugin? Would this work for you instead?
```js
module.exports = {
  // ...
  plugins: [
    // ...
    new GenerateJsonPlugin('my-file.json', require('./source.js'))
  ]
  // ...
};
```

I would prefer to have this plugin remain as simple as possible, and be responsible for only one thing: taking a JSON object and serializing it as a webpack asset.

**Comment by bipycxp** [comment]
@elliottsj, yes, it works, but I prefer more nicely solutions for my eyes 😄

**Comment by bipycxp** [comment]
@elliottsj, in the morning I thought that my decision is bad. With it i can't do something like:
```javascript
new GenerateJsonPlugin('my-file.json', '{"foo":"bar"}')
```
We can check string for a valid JSON or path to source, but it overhead.

**Comment by elliottsj** [comment]
Hey, yea, so I don't think this is something that I want to support, unfortunately. Feel free to use/publish your forked version if you like.
