### ISSUE TITLE
Can you use require/loaders in this?

### ISSUE THREAD

**Issue by halkeye** [elliottsj/generate-json-webpack-plugin#5]
I want to create a manifest file, so want to have the links to the various icon image asset it needs.

Does this have any sort of require support? I'm pretty sure plugin's don't have this kind of access, but I thought I'd check.

**Comment by elliottsj** [comment]
That's not possible with this plugin, unfortunately. You may have luck creating your own plugin and accessing the `compilation.getStats().toJson().assets` array; that should contain the filenames of your assets from your main bundle, including image assets:
```js
// webpack.config.js

module.exports = {
  // ...
  plugins: [
    {
      apply(compiler) {
        compiler.plugin('emit', (compilation, done) => {
          const assets = compilation.getStats().toJson().assets;
          // create your manifest file here...
        });
      }
    }
  ],
  // ...
};
```
