### ISSUE TITLE
0.3.0 release fails installations on version6 of Node.js (includes LTS)

### ISSUE THREAD

**Issue by leoselig** [elliottsj/generate-json-webpack-plugin#61]
We have the Node.js LTS release [`6.9.0`](https://nodejs.org/en/blog/release/v6.9.0/) in place and the release of `generate-json-webpack-plugin@0.3.0` introduced the `package.json#engine`-field for `"node": ">=6.11.5"`. This breaks installtions with the following message:

```
error generate-json-webpack-plugin@0.3.0: The engine "node" is incompatible with this module. Expected version ">=6.11.5".
error An unexpected error occurred: "Found incompatible module".
```

This change was introduced by 50e77c5b0d404a84a8b0e7e3cbaa8ebe2e9a7643.

Since this was a minor update it breaks SemVer from our point of view. Correct?

**Comment by elliottsj** [comment]
Good catch; I forgot why I added the engines field to package.json. I think I added [to match webpack@4.1.1](https://github.com/webpack/webpack/blob/41bb63ad69d0f32c042e74e732cb045b5966c452/package.json#L70-L72), but this package should still work with older webpack versions.

I'll remove it and publish 0.3.1 shortly.

**Comment by elliottsj** [comment]
0.3.1 is published!
